language: go
go:
  - 1.6
  - 1.7.5
  - 1.8
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go env
  - go get github.com/mattn/goveralls
  - go get github.com/hawkingrei/freecache 

script:
  - go  test -v ./...

after_success:
  - go test 
  - $HOME/gopath/bin/goveralls -repotoken xMww1fDInxOtV4n4fAuByCM5sMuGYmVYB 

